{
    'name': 'Employee life cycle',
    'version': '1.0',
    'summary ': 'details of ABC',
    'sequence': 10,
    'category': 'Productivity',
    'license': 'LGPL-3',
    'depends': ['hr', 'recruit_inherit', 'Itax_calculation_master', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'views/employee_cycle.xml',
        'views/report_menus.xml',
        'views/employee_application.xml',
        'views/state_insurance_corporation.xml',
        'views/nomination_and_declaration.xml',
        'views/employee.xml',
        'views/confirmation_order.xml',
        'views/letter_of_arrangement.xml',
        'views/letter.xml',
        'views/appview.xml',
        'views/employment_direct_confirmation.xml',
        'views/contract_apprenticeships.xml',
        'views/employee_cycle_wizard.xml',
        'views/extension_of_training_factory.xml',
        'views/employee_employee.xml',
        'views/extension_probation.xml',
        'views/service.xml',
        'views/extension_training.xml',
        'views/probation_discharge_letter.xml',
        'views/family_members.xml',
        'views/new_data.xml',
        'views/parents_policy.xml',
        'data/employee_records_post.xml',
        'data/create_new_employee.xml',
        'reports/insurance_corporation_report.xml',
        'reports/confirmation_report.xml',
        'reports/nomination_and_declaration_template.xml',
        'reports/letter_of_arrangemen_report.xml',
        'reports/employement_letter.xml',
        'reports/employee_confirmation_report.xml',
        'reports/training.xml',
        'reports/contract_apprenticeship.xml',
        'reports/life_cycle_report.xml',
        'reports/extension_of_training_report.xml',
        'reports/employee_report.xml',
        'reports/extension_probation_report.xml',
        'reports/extension_training_report.xml',
        'reports/servicesreport.xml',
        'reports/probation_discharge_letter_report.xml',
        'reports/family_membersreport.xml',
        'reports/new_datareport.xml',
        'reports/parent_policyreport.xml',
        'reports/employee_application_form.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'employee_life_cycle/static/js/dashboard_elc.js',
            'employee_life_cycle/static/xml/dashboard_elc.xml',
        ],
    },
    'installable ': True,
    'application': True,
    'auto_install': False,
}
