from . import resignation_request
from . import superannuation_relieving
from . import service_relieving
from . import superannuation_intimation_letters
from . import trainee_discharge
from . import resigned_relieving
from . import apprenticeship_resign_relieving
from . import certificates_from_account_department
from . import staff_canteen_certificates
from . import knowledge_center_certificates
from . import hr_dept
from . import store_department
from . import electronic_department
from . import ushodaya_hr
from . import apprentice
from . import clerancy
from . import gslic
