# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Interview Form',
    'version': '0.1',
    'summary': 'Recruitment form',
    'sequence': 10,
    'author': 'Prime Minds Consulting Pvt Ltd',
    'company': 'Prime Minds Consulting Pvt Ltd',
    'maintainer': 'Prime Minds Consulting Pvt Ltd',
    'website': "https://www.primeminds.co/",
    'description': """ Unit Master,Section Master,Medical Details,Retirement age,Updated Interview Form,Account Holder Name""",
    'category': 'Recruitmenting',
    'depends': ['recruitment_management', 'hr', 'Itax_calculation_master', 'base', 'hrms','hr_holidays'],
    'data': [
        'security/ir.model.access.csv',
        'views/emp_details.xml',
        'views/view_interview_form.xml',
        'views/view_private_info.xml',
        'views/change_hr_settings.xml',
        'views/view_qualification.xml',
        'views/view_unit_master.xml',
        'views/view_section_master.xml',
        'views/view_company_settings.xml',
        'views/view_family_details.xml',
        'views/view_invisibling_fields.xml',
        'views/self_service_sub_menu.xml',
        'views/self_service_leave_request.xml',
        'views/self_service_shift.xml',
        'views/self_service_ontour.xml',
        'views/self_service_authorize.xml',
        'views/self_service_rectification.xml',
        'views/self_service_lta.xml',
        'views/tour_expenses_bill.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
