from . import sale_order
from . import scheduling_positions_details
from . import newspaper_page_details
from . import model
from . import reta_dashboard
from . import advertisement_position
from . import sale_document_type
from . import account_payment
from . import publication_details
from . import product_pricelist
from . import reta_region
from . import res_partner
from . import multi_discount
from . import hr_employee
from . import mgmt_management_dashboard
from . import product_product
from . import account_tax
from . import category_discount
from . import multi_publish_date
from . import page_master
from . import ads
from . import pagemaster
from . import mrv
from . import nap_sequence_tracker
from . import nap_scheduling_details
from . import agent_comission
from . import agent_type
from . import ins_region
from . import important_dates
