# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Eenadu Reta',
    'version': '1.0.0',
    'category': 'Apps',
    'summary': 'Custom Sales',
    'description': 'Sales Enhancement',
    'sequence': '10',
    'author': 'Prime Minds Consulting Pvt Ltd',
    'company': 'Prime Minds Consulting Pvt Ltd',
    'maintainer': 'Prime Minds Consulting Pvt Ltd',
    'website': "https://www.primeminds.co/",
    'license': 'LGPL-3',
    'depends': [
        'sale','stock','sale_stock','sales_team','sales_circulation','web','web_tour',
    ],
    'demo': [],
    'data': [
        'data/Page_values_updation.xml',
        # 'data/cron.xml',
        'data/values_update.xml',
        'security/ir.model.access.csv',
        'security/access_group.xml',
        'wizard/scheduling_line_update_wizard_views.xml',
        'wizard/create_payment_views.xml',
        'views/sale_order_views.xml',
        'views/sales_custom.xml',
        'views/newspaper_page_details_views.xml',
        'views/page_masterinfo.xml',
        'views/advertisement_position_views.xml',
        'views/views.xml',
        'views/advertisement_position_views.xml',
        'views/sale_document_type_views.xml',
        'views/account_payment_views.xml',
        'views/agent_commission_website.xml',
        'views/employee_incentive.xml',
        'views/scheduling_position_details_views.xml',
        'views/publication_details_view.xml',
        'views/reta_regions_view.xml',
        'views/category_discount.xml',
        'views/multi_discount.xml',
        'views/res_partner.xml',
        'views/reta_dashboard.xml',
        'views/hr_employee.xml',
        'views/reta_mgmt_dashboard.xml',
        'views/product_product.xml',
        'views/ads.xml',
        'views/pageinfo.xml',
        'views/pagemaster.xml',
        'views/mrv.xml',
        # 'views/advertisement_material.xml',
        'views/nap_scheduling_details_views.xml',
        'views/imp_dates.xml',
        'views/agent_type.xml',
        'views/ins_region.xml',
        'views/agent_comission_view.xml',
        'views/title_customer.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'eenadu_reta/static/src/js/chart_2.9.4.js',
            'eenadu_reta/static/src/js/reta_dashboard.js',
            'eenadu_reta/static/src/xml/reta_dashboard.xml',
            'eenadu_reta/static/src/js/reta_management_dashboard.js',
            'eenadu_reta/static/src/xml/mgmt_dashboard.xml',
            'eenadu_reta/static/src/css/stylesheet.css',
            'eenadu_reta/static/src/css/mgmt_dashboard_ss.css',
            # 'eenadu_reta/static/src/css/boostrap.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/banner.png'],
}

